/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2017-04-08 10:28:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <!-- This file has been downloaded from Bootsnipp.com. Enjoy! -->\r\n");
      out.write("    <title>login - Bootsnipp.com</title>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        body\r\n");
      out.write("{\r\n");
      out.write("    background: url(http://www.harrisartscenter.com/wp-content/uploads/2011/09/Navy-Background.png) fixed;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrap\r\n");
      out.write("{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    min-height: 100%;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    z-index: 99;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p.form-title\r\n");
      out.write("{\r\n");
      out.write("    font-family: 'Open Sans' , sans-serif;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #FFFFFF;\r\n");
      out.write("    margin-top: 20%;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    letter-spacing: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form\r\n");
      out.write("{\r\n");
      out.write("    width: 250px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.login input[type=\"text\"], form.login input[type=\"password\"]\r\n");
      out.write("{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 5px 10px;\r\n");
      out.write("    background: 0;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    border-bottom: 1px solid #FFFFFF;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    font-style: italic;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("    color: #FFFFFF;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.login input[type=\"submit\"]\r\n");
      out.write("{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    margin-top: 16px;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.login input[type=\"submit\"]:hover\r\n");
      out.write("{\r\n");
      out.write("    transition: background-color 0.5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.login .remember-forgot\r\n");
      out.write("{\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin: 10px 0 0 0;\r\n");
      out.write("}\r\n");
      out.write("form.login .forgot-pass-content\r\n");
      out.write("{\r\n");
      out.write("    min-height: 20px;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("form.login label, form.login a\r\n");
      out.write("{\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    color: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.login a\r\n");
      out.write("{\r\n");
      out.write("    transition: color 0.5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.login a:hover\r\n");
      out.write("{\r\n");
      out.write("    color: #2ecc71;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pr-wrap\r\n");
      out.write("{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    min-height: 100%;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    z-index: 999;\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".show-pass-reset\r\n");
      out.write("{\r\n");
      out.write("    display: block !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pass-reset\r\n");
      out.write("{\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    width: 250px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin-top: 22%;\r\n");
      out.write("    z-index: 999;\r\n");
      out.write("    background: #FFFFFF;\r\n");
      out.write("    padding: 20px 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pass-reset label\r\n");
      out.write("{\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pass-reset input[type=\"email\"]\r\n");
      out.write("{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin: 5px 0 0 0;\r\n");
      out.write("    padding: 5px 10px;\r\n");
      out.write("    background: 0;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    border-bottom: 1px solid #000000;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    font-style: italic;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("    color: #000000;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pass-reset input[type=\"submit\"]\r\n");
      out.write("{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pass-reset input[type=\"submit\"]:hover\r\n");
      out.write("{\r\n");
      out.write("    transition: background-color 0.5s ease;\r\n");
      out.write("}\r\n");
      out.write(".posted-by\r\n");
      out.write("{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 26px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    color: #FFF;\r\n");
      out.write("    background-color: rgba(0, 0, 0, 0.66);\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    left: 45%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("    <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"navbar-header\">\r\n");
      out.write("    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("      <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("      <span class=\"icon-bar\"></span>\r\n");
      out.write("      <span class=\"icon-bar\"></span>\r\n");
      out.write("      <span class=\"icon-bar\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\">SHCB</a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("                <ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-home icon-white\"></i> Devices</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider-vertical\"></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-file icon-white\"></i> Board</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider-vertical\"></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-envelope icon-white\"></i> Recent activity</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider-vertical\"></li>\r\n");
      out.write("                  \t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!--/.navbar -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-12\">\r\n");
      out.write("            <div class=\"pr-wrap\">\r\n");
      out.write("                <div class=\"pass-reset\">\r\n");
      out.write("                    <label>\r\n");
      out.write("                        Enter the email you signed up with</label>\r\n");
      out.write("                    <input type=\"email\" placeholder=\"Email\" />\r\n");
      out.write("                    <input type=\"submit\" value=\"Submit\" class=\"pass-reset-submit btn btn-success btn-sm\" />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"wrap\">\r\n");
      out.write("                <p class=\"form-title\">\r\n");
      out.write("                    Sign In</p>\r\n");
      out.write("                <form class=\"login\">\r\n");
      out.write("                <input type=\"text\" placeholder=\"Username\" />\r\n");
      out.write("                <input type=\"password\" placeholder=\"Password\" />\r\n");
      out.write("                <input type=\"submit\" value=\"Sign In\" class=\"btn btn-success btn-sm\" />\r\n");
      out.write("                <div class=\"remember-forgot\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"checkbox\">\r\n");
      out.write("                                <label>\r\n");
      out.write("                                    <input type=\"checkbox\" />\r\n");
      out.write("                                    Remember Me\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 forgot-pass-content\">\r\n");
      out.write("                            <a href=\"javascript:void(0)\" class=\"forgot-pass\">SignUp?</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" $(document).ready(function () {\r\n");
      out.write("    $('.forgot-pass').click(function(event) {\r\n");
      out.write("      $(\".pr-wrap\").toggleClass(\"show-pass-reset\");\r\n");
      out.write("    }); \r\n");
      out.write("    \r\n");
      out.write("    $('.pass-reset-submit').click(function(event) {\r\n");
      out.write("      $(\".pr-wrap\").removeClass(\"show-pass-reset\");\r\n");
      out.write("    }); \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
