/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2017-04-08 11:22:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SignUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "SignUp.css", out, false);
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xs-12 col-sm-12 col-md-4 well well-sm\">\r\n");
      out.write("            <legend><a href=\"http://www.jquery2dotnet.com\"><i class=\"glyphicon glyphicon-globe\"></i></a> Sign up!</legend>\r\n");
      out.write("            <form action=\"#\" method=\"post\" class=\"form\" role=\"form\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xs-6 col-md-6\">\r\n");
      out.write("                    <input class=\"form-control\" name=\"firstname\" placeholder=\"First Name\" type=\"text\"\r\n");
      out.write("                        required autofocus />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xs-6 col-md-6\">\r\n");
      out.write("                    <input class=\"form-control\" name=\"lastname\" placeholder=\"Last Name\" type=\"text\" required />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input class=\"form-control\" name=\"youremail\" placeholder=\"Your Email\" type=\"email\" />\r\n");
      out.write("            <input class=\"form-control\" name=\"reenteremail\" placeholder=\"Re-enter Email\" type=\"email\" />\r\n");
      out.write("            <input class=\"form-control\" name=\"password\" placeholder=\"New Password\" type=\"password\" />\r\n");
      out.write("            <label for=\"\">\r\n");
      out.write("                Birth Date</label>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xs-4 col-md-4\">\r\n");
      out.write("                    <select class=\"form-control\">\r\n");
      out.write("                        <option value=\"Month\">Month</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xs-4 col-md-4\">\r\n");
      out.write("                    <select class=\"form-control\">\r\n");
      out.write("                        <option value=\"Day\">Day</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xs-4 col-md-4\">\r\n");
      out.write("                    <select class=\"form-control\">\r\n");
      out.write("                        <option value=\"Year\">Year</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <label class=\"radio-inline\">\r\n");
      out.write("                <input type=\"radio\" name=\"sex\" id=\"inlineCheckbox1\" value=\"male\" />\r\n");
      out.write("                Male\r\n");
      out.write("            </label>\r\n");
      out.write("            <label class=\"radio-inline\">\r\n");
      out.write("                <input type=\"radio\" name=\"sex\" id=\"inlineCheckbox2\" value=\"female\" />\r\n");
      out.write("                Female\r\n");
      out.write("            </label>\r\n");
      out.write("            <br />\r\n");
      out.write("            <br />\r\n");
      out.write("            <button class=\"btn btn-lg btn-primary btn-block\" type=\"submit\">\r\n");
      out.write("                Sign up</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
